### ISSUE TITLE
Improve "formatting" of Guidelines

### ISSUE THREAD

**Issue by dzacharo** [cabforum/servercert#141]
The first versions of the Guidelines used a lot of copy-paste from other formats (mostly Microsoft Word). During this process, we currently see lots of double spaces and other "Markdown-unfriendly" paragraphs on GitHub. 

We should try to update the existing versions without modifying language, numbering or any text, in order to create versions that are more "Markdown-friendly" and can produce better visual results in various Markdown viewers.

**Comment by sleevi** [comment]
I think this will be closed by https://github.com/cabforum/documents/pull/165

@castillar

**Comment by sleevi** [comment]
@castillar Marking this as Closed based on the Pandoc cleanup
