### ISSUE TITLE
NetSec: suggested CVSS updates

### ISSUE THREAD

**Issue by bdaehlie** [cabforum/servercert#156]
Passing this report/suggestion along from a community member.

Relating to the definition of "Critical Vulnerability":

1. This link seems outdated:

http://nvd.nist.gov/home.cfm

Perhaps a better link would be:

https://nvd.nist.gov/vuln-metrics/cvss

This also has the advantage of being an https link.

2. CVSS v3.0 defines critical as 9.0 or above. The NetSec guidelines currently say CVSS 7.0 or higher is critical. Should the NetSec guidelines be changed to define critical as 9.0, in line with the CVSS ratings, or is NetSec intentionally lowering the bar for what's considered critical to 7.0?

**Comment by dzacharo** [comment]
The issue was properly forwarded to the NetSec Subcommittee of the Server Certificate Working Group.

**Comment by sleevi** [comment]
These were fixed in SC39 in 34ce8e09dfa43229db8efaa7f2958e046bafea74
