### ISSUE TITLE
Baseline Requirements: Replace 3.2.2.5.6/.7 with RFC 8738

### ISSUE THREAD

**Issue by sleevi** [cabforum/servercert#169]
3.2.2.5.6 / 3.2.2.5.7 reference https://tools.ietf.org/html/draft-ietf-acme-ip-04

This is now published as RFC 8738. The references should be updated, presumably through the introduction of a new method.

You can see the diff between draft-04 and the final RFC at http://tools.ietf.org/tools/rfcdiff/rfcdiff.pyht?url1=https://tools.ietf.org/id/draft-ietf-acme-ip-04.txt&url2=https://tools.ietf.org/rfc/rfc8738.txt

**Comment by ryancdickson** [comment]
@barrini - seems like this could be included in the clean-up ballot (I don't have perms to add the label).

**Comment by barrini** [comment]
Yes, agree. I´ll try to add the label

**Comment by barrini** [comment]
Included in fall 2023 clean-up ballot
