### ISSUE TITLE
Baseline Requirements: "Log entries" in 5.4.1 is ambiguous

### ISSUE THREAD

**Issue by sleevi** [cabforum/servercert#180]
As raised by Trev [on the servercert-wg list](https://cabforum.org/pipermail/servercert-wg/2020-May/001922.html), the wording in section 5.4.1 is ambiguous.

At question is whether "log entries" in the following:
https://github.com/cabforum/documents/blob/6e0b8e61590164eb2d686ddcf266b189f46fc636/docs/BR.md#L1318-L1322

refers to 3.f
https://github.com/cabforum/documents/blob/6e0b8e61590164eb2d686ddcf266b189f46fc636/docs/BR.md#L1316
or whether it refers to the overall section 5.4.1
https://github.com/cabforum/documents/blob/6e0b8e61590164eb2d686ddcf266b189f46fc636/docs/BR.md#L1293

**Comment by barrini** [comment]
F2F 60 decision to close
