### ISSUE TITLE
EV Guidelines: Don't require the Tor Service Descriptor Hash for v3 onion names

### ISSUE THREAD

**Issue by sleevi** [cabforum/servercert#190]
In [SC27](https://cabforum.org/2020/02/20/ballot-sc27v3-version-3-onion-certificates/), support for [v3 onion addresses](https://gitweb.torproject.org/torspec.git/tree/rend-spec-v3.txt) was introduced, allowing both DV and OV certificates to be issued.

Support for [v2 onion addresses](https://gitweb.torproject.org/torspec.git/tree/rend-spec-v2.txt) was intentionally not removed from the EV Guidelines, in order to allow continued usage of existing names.

While Appendix F of the EV Guidelines was updated to permit the issuance of V3 addresses, provided they're validated as described within Appendix C of the Baseline Requirements, the normative requirement within Appendix F to include the Tor Service Descriptor hash was not removed.

As discussed in and during SC27, the Tor Service Descriptor hash is not necessary for V3 certificates.

In the current form, this creates a challenge for CAs, in that if the issued certificate is DV/OV/IV, and the address is V3, the extension is not needed, but if the certificate is EV, the extension is still required to be included. Given that it's not necessary to include this extension for v3 addresses, the requirement should be normalized (as not required) across all profiles.

**Comment by sleevi** [comment]
Another ambiguity: Is it a prohibited to include the Tor Service Descriptor hash in a DV/OV/IV certificate (that is, for a v3 address)

Saying it's not required is one thing, saying it's not permitted is another, and things should be clearer.

**Comment by CBonnell** [comment]
This was resolved with SC54.
