### ISSUE TITLE
EV Guidelines: Clarify that v2 .onion names need to be well formed

### ISSUE THREAD

**Issue by sleevi** [cabforum/servercert#191]
**Note: I believe this is an existing requirement in the text, and this is merely to make it unambiguously so.**

When the CA/Browser Forum introduced [Ballot 144](https://cabforum.org/2015/02/18/ballot-144-validation-rules-dot-onion-names/), in 2015-02, permitting `.onion` domains, there was no special reservation for `.onion` by the IESG/IANA. That reservation did not happen until 2015-10, with the adoption of [RFC 7686](https://tools.ietf.org/html/rfc7686).

The language drafted in Ballot 144, and which largely has been maintained in its current form, requires that CA validate the Applicant's control over the `.onion` name by virtue of either demonstrating proof of possession of the public key or through connection to the `.onion` service. However, it makes no requirements about how the `.onion` name is formed/validated.

This ambiguity was resolved by RFC 7686, which normatively depends on the Tor address and rendezvous specifications, which then define the addressing form for v2 onion addresses (i.e. the base-32 encoding of the first 80 bits of the SPKI hash), and has later been updated to define v3 onion addresses as well.

[Ballot SC27v3](https://cabforum.org/2020/02/20/ballot-sc27v3-version-3-onion-certificates/) unambiguously refers to the v3 specification for address creation, so the only potential ambiguity for CAs is with respect to whether or not those addresses formed and validated, according to Appendix F of the EV Guidelines, need to be well-formed according to the rendezvous specification.

I believe it is, for the following reasons:
  * RFC 7686 normatively depends on these specifications for the creation of `.onion` names
  * The EV Guidelines, by requiring a service either be connected to (which fundamentally requires the address be well-formed; Appendix F (2)(a)) or requires the CA validate the public key (which thus requires the CA to construct a `.onion` name according to that public key to ensure the relationship; Appendix F (2)(b)), functionally requires this

However, it wouldn't hurt in future work to be unambiguous that such addresses must be well-formed

**Comment by dzacharo** [comment]
According to the [Onion Service version 2 deprecation timeline](https://blog.torproject.org/v2-deprecation-timeline), v2 addresses will be disabled on October 15, 2021. Should the SCWG proceed with a similar deprecation plan to disallow v2 Onion addresses in EV Certificates with SHOULD NOT after 2021-10-15 and MUST NOT after 2022-10-15?

**Comment by sleevi** [comment]
@dzacharo Could you explain how you came up with those dates? It seems MUST NOT after 2021-10-15 is in line with the actual timeline, so why allow issuance after-the-fact?

**Comment by dzacharo** [comment]
I understood that they will still accept v2 for old versions of the Tor client, but if I have not understood correctly and we must deprecate sooner, I have no objections :)

**Comment by sleevi** [comment]
Gotcha; and not quite.
2021-07-15: No *new* clients will accept v2
2021-10-15: All *old* clients will be updated to remove v2

So, effectively, 2021-10-15 is when v2 stops working everywhere.

**Comment by CBonnell** [comment]
BR Appendix B makes it clear that Onion Domain Names must be well-formed:

> The Domain Name MUST contain at least two Domain Labels, where the rightmost
Domain Label is “onion”, and the Domain Label immediately preceding the
rightmost “onion” Domain Label is a valid Version 3 Onion Address, as defined in
Section 6 of the Tor Rendezvous Specification ‐ Version 3 located at
https://spec.torproject.org/rend‐spec‐v3.

Given this, I believe this issue can be closed.
