### ISSUE TITLE
BRs: Clarify that the problem reporting method must be itself be available via a readily accessible online means

### ISSUE THREAD

**Issue by sleevi** [cabforum/servercert#201]
In Mozilla [Bug 1650234](https://bugzilla.mozilla.org/show_bug.cgi?id=1650234), a discussion about the problem reporting method a particular CA used and documented within their CP/CPS met the expectations of browsers and the Baseline Requirements. The CP/CPS provided a contact e-mail within Section 1.5.2, but provided a supplementary Section 1.5.2.1 to be used for reporting specific events, and that was restricted in who can access that portal.

While there's nothing inherently problematic with having a problem reporting mechanism available specifically to Subscribers, the concern is whether or not the CA must also maintain a problem reporting mechanism for "other third parties", as described in Section 4.9.3 of the BRs.

That is, 4.9.3 requires that:
> The CA SHALL provide Subscribers, Relying Parties, Application Software Suppliers, and other third parties
> with clear instructions for reporting suspected Private Key Compromise, Certificate misuse, or other types of
> fraud, compromise, misuse, inappropriate conduct, or any other matter related to Certificates. The CA SHALL
> publicly disclose the instructions through a readily accessible online means and in section 1.5.2 of their CPS.

However, there's some ambiguity as to whether the only the instructions need to be available through a readily accessible online means, or whether the CA must also provide a problem reporting mechanism itself through a readily accessible online means.

This modification was introduced in [CA/B Forum Ballot SC6](https://cabforum.org/2018/09/14/ballot-sc6-revocation-timeline-extension/), which was parallel to [a Mozilla discussion](https://github.com/mozilla/pkipolicy/issues/98) about requiring CAs to support problem reporting via e-mail. While Mozilla ultimately declined to mandate e-mail (as opposed to other technologies), it's believed the intent was to at least support some form of readily accessible online means of problem reporting.

The language here can be clarified, and perhaps shifted in its requirements from 4.9.3 to 1.5.2 to greater emphasize the expectation of content by normatively describing it within that section.

**Comment by timfromdigicert** [comment]
I would argue that if "instructions for XXX" cannot result in the completion of the goal XXX, then they are not actually "instructions for XXX."

E.g. "In order to report key compromise, write the compromised key on a piece of paper and burn it." does not qualify as "instructions for reporting key compromise."

**Comment by mpalmer** [comment]
Whilst burning the paper wouldn't qualify as instructions, requiring reporters to put the paper in an envelope, put an address and stamp on the envelope, and drop it in a mail box *would* count as "instructions".  As I read the current BR language, requiring all reports to be sent via registered post would be BR compliant -- but an absolutely terrible outcome for the Web PKI.

I'd like to highlight that just changing the wording to say that the problem reporting method must be "readily accessible online" may not be sufficient.  Another CA (separate to the one mentioned up-bug) is [suggesting that an ACME revokeCert endpoint](https://bugzilla.mozilla.org/show_bug.cgi?id=1639804) is a sufficient means for everyone to report key compromise.  Whilst I do love ACME, I am concerned that requiring everyone who wants to report key compromise to figure out how to use ACME will have the inevitable effect of causing some problems to go unreported.  Anything that has the result of reducing the number of valid problem reports must meet an *extremely* high bar, in my opinion, to be justifiable.

It would be helpful if a change to the current wording were such as to make it clear what "readily accessible" means.  Having tried to draft language that would do so, and failing spectacularly, I know that this is not easy, but hopefully someone who is a more skilled wordsmith than I is up to the challenge.

**Comment by barrini** [comment]
F2F 60 decision to close
