### ISSUE TITLE
EV Guidelines: Wrong cross-reference to BRs in Section 18

### ISSUE THREAD

**Issue by BenWilson-Mozilla** [cabforum/servercert#215]
Section 18 of the EVGs says, "CAs MAY limit their liability as described in Section 18 of the Baseline Requirements except that a CA MAY NOT limit its liability to Subscribers or Relying Parties for legally recognized and provable claims to a monetary amount less than two thousand US dollars per Subscriber or Relying Party per EV Certificate."  This section number doesn't exist in the Baseline Requirements.  
I believe the correct cross-reference would be to section 9.8 of the Baseline Requirements.

**Comment by sleevi** [comment]
Forgot to close this out. This was fixed by [SC41](https://cabforum.org/2021/02/26/ballot-sc41-reformatting-the-brs-evgs-and-ncssrs/) in 3df1fbc0d0ea14f8163d6fed6c64b1dc90dfee77
