### ISSUE TITLE
BR: No audit schemes in Section 8.1

### ISSUE THREAD

**Issue by MMeent** [cabforum/servercert#216]
> ## 8.1 Frequency or circumstances of assessment
> [...]
> If the CA has a currently valid Audit Report indicating compliance with an audit scheme listed in Section 8.1 [...]

Section 8.1 self-references for finding audit schemes, but all audit schemes that were called out as being audit schemes I could find in the document were from Section 8.4. 

As a lot of places reference "an audit scheme as specified in Section 8.1" or something similar, I believe this is a bug / list of bugs that should be fixed.

**Comment by sleevi** [comment]
Thanks, I thought we’d filed a bug on this, as it came up during a recent Ballot review and was pointed out by @BenWilson-Mozilla , but it looks like I forgot to file the bug.
