### ISSUE TITLE
BRs: Fix language in APPENDIX B 

### ISSUE THREAD

**Issue by dzacharo** [cabforum/servercert#240]
In APPENDIX B replace:

"The CA MAY verify the Applicant's control over the .onion service by having the Applicant provide a Certificate Request signed using the .onion public key"

with

"The CA MAY verify the Applicant's control over the .onion service by having the Applicant provide a Certificate Request signed using the .onion **private** key"

**Comment by CBonnell** [comment]
Fixed in BR Appendix B with SC54:
>The CA MAY verify the Applicant’s control over the .onion service by having
the Applicant provide a Certificate Request signed using the .onion service’s
private key
