### ISSUE TITLE
Formatting and numbering of 3.2.2.4.4 is broken starting in BR v1.7.1.

### ISSUE THREAD

**Issue by timfromdigicert** [cabforum/servercert#253]
The formatting of section 3.2.2.4.4 is broken.  I haven't determined which ballot did it, or whether it was a merge error. 
But as you see below, the enumerated list is handled incorrectly.

Section 3.2.2.4.4, BR v1.7.1:

Confirm the Applicant’s control over the FQDN by 1. Sending an email to one or more
addresses created by using ‘admin’, ‘administrator’, ‘webmaster’, ‘hostmaster’, or
‘postmaster’ as the local part, followed by the at-sign (“@”), followed by an Authorization
Domain Name; and 1. including a Random Value in the email; and 1. receiving a confirming
response utilizing the Random Value.

Section 3.2.2.4.4, BR v1.7.0:

Confirm the Applicant's control over the FQDN by
1. sending an email to one or more addresses created by using 'admin', 'administrator', 'webmaster',
'hostmaster', or 'postmaster' as the local part, followed by the at-sign ("@"), followed by an
Authorization Domain Name,
2. including a Random Value in the email, and
3. receiving a confirming response utilizing the Random Value

**Comment by sleevi** [comment]
@timfromdigicert This was already fixed in SC41v2.

**Comment by sleevi** [comment]
Fixed by 3df1fbc0d0ea14f8163d6fed6c64b1dc90dfee77
