### ISSUE TITLE
CA is prohibited from signing own server certs

### ISSUE THREAD

**Issue by MMeent** [cabforum/servercert#255]
in s6.1.1.3:

> If the Subscriber Certificate will contain an extKeyUsage extension containing either the values id-kp-serverAuth [RFC5280] or anyExtendedKeyUsage [RFC5280], the CA SHALL NOT generate a Key Pair on behalf of a Subscriber, and SHALL NOT accept a certificate request using a Key Pair previously generated by the CA.

This contains the suprising constraint (when taken literally) that CAs may not sign their own server certificates as long as they themselves generated the key described in that certificate. 

Simply changing it to "and SHALL NOT accept a certificate request from a Subscriber that uses/describes a Key Pair previously generated by the CA." should make the intended meaning clear.

**Comment by sleevi** [comment]
Thanks for filing this! I don’t think the proposed language is the right fix; it both doesn’t say anything new and weakens the existing restriction (e.g. it can imply new key generation is allowed). We can try to find better language though.

**Comment by sleevi** [comment]
Can you clarify if you’ve signed the IPR Agreement? I’m not seeing it based on the GitHub ID.

**Comment by MMeent** [comment]
I wouldn't know which IPR Agreement I would need to have signed for this repository (can't easily find it mentioned anywhere).

(after some searching) Apparently https://github.com/cabforum/servercert/blob/main/.github/contributing.md contains information about that? That wasn't as discoverable as I'd hoped.

Apart from that, I'm not 1.) a CA, nor 2.) a Certificate Consumer (as described in https://cabforum.org/information-for-potential-members/), I'm merely a Relying Party, so I'm not certain I am even allowed to contribute to these documents as per the first requirement in the .github/contributing.md document and the requirements set forth in https://cabforum.org/information-for-potential-members/

**Comment by sleevi** [comment]
Yes, the Contributing Guidelines are linked by GitHub when opening issues. You can consider joining as an interested party if you would like to contribute, or raise concerns at questions@cabforum.org

**Comment by MMeent** [comment]
Yes, but that still doesn't allow me to contribute to this repository, if I understand contributing.md file correctly:

> In order to contribute to the CA/Browser Forum repository, all contributors **must have an active membership** in the CA/Browser Forum and have executed the CA/Browser Forum's Agreement for the Intellectual Property Rights (IPR) Policy.

For membership of CA/Browser Forum, one must be issuing certificates, or a Certificate Consumer. Ergo, members the public at large cannot contribute to the BR.

---

I'll send a mail to questions@cabforum.org instead.

**Comment by timfromdigicert** [comment]
Interested Parties are Members, see the Bylaws section 2.1 (https://cabforum.org/wp-content/uploads/CA-Browser-Forum-Bylaws-v2.3.pdf).

**Comment by wthayer** [comment]
@MMeent I've made a few changes to https://cabforum.org/information-for-potential-members/ that hopefully clarify the option to join as an Interested Party.

**Comment by kyanha** [comment]
Because of the third-party attestation function, no CA should ever sign webserver certificates for its own domains, even if they've been generated by service providers.  Unless we're actively treating browsers as implicit CAs for purposes of attestation (a position I'll note that Mozilla has been unwilling to take, in that it refuses to operate its own cross-signing CA), propriety dictates that a third party needs to verify that the corporation providing the CA service (and thus the website) is who they say they are.

I realize this conflicts with the desire by CAs to prove that their own certificates are trusted by the browser being used, but since one of the fundamental requirements is that "CAs must show they understand the function of third party attestation", it makes no sense to allow this desire to advertise to override the fundamental purpose of the profession.

**Comment by clintwilson** [comment]
Fixed in [SC-066](https://cabforum.org/2023/11/24/ballot-sc-066-v4-fall-2023-clean-up/) by adding text to section 1.3.3.

**Comment by kyanha** [comment]
If CAs are required to understand the third party attestation function, why have they ever been permitted to sign their own server certs?
