### ISSUE TITLE
Baseline Requirements: Consider removing the CAA Operator Exception

### ISSUE THREAD

**Issue by sleevi** [cabforum/servercert#256]
Originally raised on [Mozilla's m.d.s.p. list](https://groups.google.com/g/mozilla.dev.security.policy/c/0TfT9BziQVc/m/gV3dqYWSAAAJ), Andrew Ayer rightfully highlighted that the current exception to CAA in 3.2.2.8 that reads:

> CAA checking is optional if the CA or an Affiliate of the CA is the DNS Operator (as defined in RFC 7719) of the domain’s DNS

There is a surprising amount of technical complexity, and so far, the CAs that have taken advantage of this have had incidents (e.x. [Microsoft](https://bugzilla.mozilla.org/show_bug.cgi?id=1670337) ). There's a lot to be said for the simplicity and security of consistent validation procedures for domains.

**Comment by hhbbbbvv** [comment]
Hi

**Comment by sleevi** [comment]
Addressed in https://cabforum.org/2021/06/02/ballot-sc46-sunset-the-caa-exception-for-dns-operator/ aka https://github.com/cabforum/servercert/pull/271
