### ISSUE TITLE
BRs: Permit 3.2.2.4.20 for onion domains?

### ISSUE THREAD

**Issue by sleevi** [cabforum/servercert#270]
Currently, Appendix B only permits 3.2.2.4.6 or "subsequent methods" (which means .18 / .19 - see #241 ) for the validation of `.onion` domains, or through the use of the special CSR documented within that section.

However, method 3.2.2.4.20 would also be suitable for use with `.onion` domains. Given its comparable security properties to .18/.19, and the desire to support robust ACME implementations (using HTTP-01 and TLS-ALPN-01 validation methods, per https://www.iana.org/assignments/acme/acme.xhtml#acme-validation-methods ), it seems that this section could be further extended to support 3.2.2.4.20.

This came up while working through #269

**Comment by clintwilson** [comment]
Fixed in [SC-054](https://cabforum.org/2022/03/24/ballot-sc54-onion-cleanup/) by adding method 3.2.2.4.20 (and 3.2.2.4.18 and 3.2.2.4.19) to an explicit list of allowed methods outlined in Appendix B.
