### ISSUE TITLE
Meta: Provide mechanism for requirement effective dates to be relative to ballot effective dates

### ISSUE THREAD

**Issue by aarongable** [cabforum/servercert#278]
Semi-hypothetical situation:
1) A ballot is proposed on 20XX-01-01; the text of the ballot includes requirements with an effective date of 20XX-07-01.
2) Discussion, debate, and revision take longer than expected.
3) The ballot is voted on and passes on 20XX-06-15.
4) Therefore its IPR review period ends (and the ballot can be published and become effective) 20XX-07-15, *after* the requirements' effective date in the text.

I propose that we create a mechanism to prevent this. Rather than directly encoding effective dates directly in the text of the ballot, authors should be able to propose requirement effective dates which are relative to the ballot effective date.

For example, ballot text could formatted as
```diff
+ If the CA follows redirects, the following apply:
+ 1. Redirects MUST be initiated at the HTTP protocol layer.
+    a. For validations performed on or after {{+30d}}, redirects MUST be the result of ...
+    b. For validations performed prior to {{+30d}}, redirects MUST be the result of ...
+ 2. Redirects MUST be to resource URLs with either the "http" or "https" scheme.
```
This `{{+Xd}}` syntax could be automatically replaced with the appropriate textual date by a GitHub Action at the time that the ballot PR is merged into the main branch of the repository.

**Comment by barrini** [comment]
Aaron to clarify

**Comment by aarongable** [comment]
At the time I filed this, I was fairly new to the CA/BF and believed we needed a systematic solution to prevent this. I now believe that our human processes are (barely) sufficient to ensure that effective dates are in the future. Closing as WontFix.
