### ISSUE TITLE
BRs: Clarify behavior if/when an effective date in the text predates its own publication date

### ISSUE THREAD

**Issue by aarongable** [cabforum/servercert#279]
Semi-hypothetical situation:
1) A ballot is introduced with includes text stating that its effective date is 20XX-07-01
2) The ballot's discussion and voting ends 20XX-06-15
3) Therefore the ballot's IPR period ends 20XX-07-15
4) Therefore the new version of the BRs is published and goes into effect 20XX-07-15

There are two reasonable interpretations of what happens for issuances between 07-01 and 07-15:
* Those issuances are not subject to the new requirement, because they occurred before the new version of the BRs was published; or
* Those issuances are subject to the new requirement, because they occurred after the effective date.

I believe that the former is technically the case. But this is not immediately clear from the text of the BRs. And it would be easy for a security researcher to assume the latter is the case and report purported misissuances based on that belief.

The text of the BRs should clarify what happens in this case. This is in addition to establishing processes to prevent this eventuality in the first place, as tracked in #278.

**Comment by barrini** [comment]
Aaron to handle
