### ISSUE TITLE
Clean up References

### ISSUE THREAD

**Issue by CBonnell** [cabforum/servercert#284]
Section 1.6.3 of the BRs uses a garden variety of formats for the various references, especially for the IETF RFCs.

Inconsistencies noted:
- Whether all authors are listed, or just the first followed by "et al"
- Whether only author last names are listed, or first name initials precede the last name
- Whether a full stop or a comma follows the document name before the author list
- Whether a full stop or a comma follows the author list before the publication date

The ordering of the RFC entries in the reference section is also inconsistent (i.e. RFC 8659 is listed before RFC 6960), which makes it harder to find a specific reference.

**Comment by sleevi** [comment]
Hah, thanks for filing this! I remember noticing it during the profiles work and deciding I didn't want to touch it there. I agree, we should definitely clean this up. I played a little with using [citation lists](https://pandoc.org/MANUAL.html#citations), but was profoundly unhappy with the output, and it seemed a lot more overkill than needed.

There was a related bit, which I learned Pandoc also supports [definition lists](https://pandoc.org/MANUAL.html#definition-lists), which may be useful for 1.6.1/1.6.2. I meant to play around with these to see if we could end up with more easily maintained style for 1.6.
