### ISSUE TITLE
BRs: Clean up 9.6.1 after OUs are forbidden

### ISSUE THREAD

**Issue by clintwilson** [cabforum/servercert#287]
If SC47 passes, or OUs otherwise become forbidden, 9.6.1 can have removed its requirement that CAs 
> implemented a procedure for reducing the likelihood that the information contained in the Certificate’s subject:organizationalUnitName attribute would be misleading;

This is quite a ways off, but thought I'd log it while I was thinking of it.

**Comment by castillar** [comment]
With the passage of [SC47](https://github.com/cabforum/servercert/pull/298), sounds like we can put this one on the list for cleanups. Is this sufficiently non-normative that we could include it in a clean-up ballot?
