### ISSUE TITLE
Baseline Requirements: Misc. Clean-Up Items

### ISSUE THREAD

**Issue by BenWilson-Mozilla** [cabforum/servercert#307]
1.2.2 Relevant Dates

Replace “Form” with “Forum” in table entry “2020‐09‐30 7.1.6.4 Subscriber Certificates …”

1.6.1 Definitions

Replace the first period with a comma in the following definition: “Certificate Profile: A set of documents or files that defines requirements for Certificate content and Certificate extensions in accordance with Section 7. e.g. …”

Add the indefinite article “a” before “cryptographic system” in “CSPRNG: A random number generator intended for use in cryptographic system.”

Replace “Validation Specialists:” with “Validation Specialist:”

1.6.3 References

For “Network and Certificate System Security Requirements” replace “v.1.0, 1/1/2013” with the CABF website URL “https://cabforum.org/network-security-requirements/”.

For “WebTrust for Certification Authorities, SSL Baseline with Network Security,” replace v.2.3 with v.2.5 and remove URL. (Or use URL of https://www.cpacanada.ca/-/media/site/operational/ms-member-services/docs/webtrust/wt100bwtbr-25-110120-finalaoda.pdf?la=en&hash=11A5FE85CBF7F0E960E681DFF6FD4592FC135B4C)

**Comment by sleevi** [comment]
Hi Ben, I'm closing this, because "misc cleanup bugs" are a bit of an anti-pattern best tracked through discrete bugs.

**Comment by sleevi** [comment]
Filed #309 #310 and #312 from this.
