### ISSUE TITLE
Redefine Technically Constrained Subordinate CA Certificate

### ISSUE THREAD

**Issue by BenWilson-Mozilla** [cabforum/servercert#314]
Replace “and” with “or” in “Technically Constrained Subordinate CA Certificate," so that it reads, "A Subordinate CA certificate which uses a combination of Extended Key Usage settings or Name Constraint settings to limit the scope within which the Subordinate CA Certificate may issue Subscriber or additional Subordinate CA Certificates.”  Then check its usage throughout the BRs and root programs to make sure they adequately describe the two conditions under which a sub CA would be considered technically constrained.

**Comment by sleevi** [comment]
This is already being tackled as part of the overall Profiles work, which is updating the definitions to match, in https://github.com/sleevi/cabforum-docs/pull/36

**Comment by BenWilson-Mozilla** [comment]
Handled by the profiles work.
