### ISSUE TITLE
Fix typos and mis-spellings

### ISSUE THREAD

**Issue by CBonnell** [cabforum/servercert#333]
Some typos and mis-spellings that should be corrected in the next clean-up ballot. I'll add more to this issue as I encounter them.

BR.md:
* "Roots CA" to "Root CA"
* "tradenames" to "trade names"
* "timeframe" to "time frame"
* "Canonicalise" to "Canonicalize" (it appears we use American spelling throughout, so this is a consistency fix more than anything)

NSR.md:
* "multifactor" to "multi-factor"

**Comment by sleevi** [comment]
According to https://archive.cabforum.org/pipermail/public/2021-December/046952.html and https://archive.cabforum.org/pipermail/public/2021-December/046979.html  discussion of the NSRs should no longer happen in the servercert WG/repo, to comply with the IPR policy.
