### ISSUE TITLE
EV Guidelines: Reverence to non existing Appendix C of BR

### ISSUE THREAD

**Issue by mimi89999** [cabforum/servercert#346]
Hello,
`Appendix F – Issuance of Certificates for .onion Domain Names` of EV Guidelines contains:
> A CA may issue an EV Certificate with "onion" as the right-most Domain Label of the Domain Name provided that issuance complies with the requirements set forth in this Appendix or Appendix C of the Baseline Requirements.

BR does not have an `Appendix C`. It does however have an `APPENDIX B – Issuance of Certificates for .onion Domain Names`.

**Comment by dzacharo** [comment]
Several issues related to Onion Certificates are being addressed in https://github.com/dzacharo/servercert/pull/4 which have been incorporated in ballot SC54 which is in the official [discussion period](https://lists.cabforum.org/pipermail/servercert-wg/2022-March/003184.html).
