### ISSUE TITLE
Fix capitalization for CAA definition in 1.6.1

### ISSUE THREAD

**Issue by castillar** [cabforum/servercert#349]
Raised by Ons Echikh Zouali over email: In section 1.6.1’s definition of CAA, the entry ‘domain name’ may need to be capitalized to ‘Domain Name’.

This would change the definition statement to:

> **CAA:** From RFC 8659 (http://tools.ietf.org/html/rfc8659): “The Certification Authority Authorization (CAA) DNS Resource Record allows a DNS Domain Name holder to specify one or more Certification Authorities (CAs) authorized to issue certificates for that Domain Name. CAA Resource Records allow a public CA to implement additional controls to reduce the risk of unintended certificate mis‐issue.”

**Comment by castillar** [comment]
Capitalization here might or might not be needed since this is a direct quote from RFC8659, which does not incorporate those capitals (because it’s not using our formal definition of the term, it’s using the RFC’s definition).

**Comment by CBonnell** [comment]
I'm in favor of keeping the language as-is, since as @castillar mentions, this is a direct quote.

**Comment by timfromdigicert** [comment]
In addition, RFC 8659 has its own definition of Domain Name, which isn't the same as the BR definition.

**Comment by CBonnell** [comment]
Based on the above, I believe consensus is that the current language is fine. Can we close this out?
