### ISSUE TITLE
Add CRL Reason Code Requirements 

### ISSUE THREAD

**Issue by BenWilson-Mozilla** [cabforum/servercert#377]
Currently, BR section 7.2.2 says, "If a reasonCode CRL entry extension is present, the CRLReason MUST indicate the most appropriate reason for revocation of the certificate, as defined by the CA within its CP/CPS."  Mozilla now has requirements that would replace this language - https://www.mozilla.org/en-US/about/governance/policies/security-group/certs/policy/#611-end-entity-tls-certificate-crlrevocation-reasons.  There is additional guidance provided here:  https://wiki.mozilla.org/CA/Revocation_Reasons.  Mozilla's CRL reason code requirements should be incorporated into section 7.2.2 of the Baseline Requirements.

**Comment by ryancdickson** [comment]
@BenWilson-Mozilla - I think this is safe to close now given SC-61?

**Comment by BenWilson-Mozilla** [comment]
Yes - I'm closing it here.
