### ISSUE TITLE
Update Section 9.6.1 regarding organizationalUnitName attributes

### ISSUE THREAD

**Issue by dzacharo** [cabforum/servercert#397]
This was spotted by Wendy Brown.

Section 9.6.1 should have been updated with the ballot that prohibited OrgUnits in DNs 

>     4. No Misleading Information: That, at the time of issuance, the CA
> 
>         i. implemented a procedure for reducing the likelihood that the information contained in the Certificate’s subject:organizationalUnitName attribute would be misleading;

We should remove this sub-item since OUs are not allowed since Oct 1, 2022.

**Comment by CBonnell** [comment]
This has been addressed as part of SC-56: https://github.com/cabforum/servercert/pull/385/files#diff-e0ac1bd190515a4f2ec09139d395ef6a8c7e9e5b612957c1f5a2dea80c6a6cfeL2491

**Comment by dzacharo** [comment]
Thanks Corey .
