### ISSUE TITLE
The title of the TLS BR should include a reference to TLS/serverAuth 

### ISSUE THREAD

**Issue by srdavidson** [cabforum/servercert#420]
It has been pointed out that the CABF now has several "baseline requirements" and that the "Baseline Requirements for the Issuance and Management of Publicly-Trusted Certificates" does not adequately describe the type of certificates.  This can create confusion.  By contrast, the code signing and S/MIME documents name the certificate type in their titles.

The Server Cert WG should consider updating the name of the TLS BR to specifically identify TLS serverAuth certificates.

**Comment by barrini** [comment]
Agreed.

**Comment by ryancdickson** [comment]
+1

**Comment by BenWilson-Mozilla** [comment]
This is a duplicate of Issue #337

**Comment by barrini** [comment]
Already done.
