### ISSUE TITLE
Clarify maximum period for DCV usage

### ISSUE THREAD

**Issue by XolphinMartijn** [cabforum/servercert#430]
BR Section 4.2.1 states

"_For validation of Domain Names and IP Addresses according to Section 3.2.2.4 and 3.2.2.5, any reused data, document, or completed validation MUST be obtained no more than 398 days prior to issuing the Certificate._"

This could be interpreted as meaning "_any reused data, [reused] document, or [reused] completed validation MUST be obtained no more than 398 days prior to issuing the Certificate._", meaning that as long as a DCV is used only once, it does not have to fall within the 398 day window.

Suggest updating this language to remove the word "reused" from the sentence, which should more clearly state the original intention of this requirement.

**Comment by vanbroup** [comment]
What about: "_For validation of Domain Names and IP Addresses according to Section 3.2.2.4 and 3.2.2.5, any data, document, or completed validation MAY NOT be reused more than 398 days from the time this information was validated._"

**Comment by barrini** [comment]
Suggest " ... 3.2.2.5, any data, document, or completed validation SHALL NOT be used more than 398 days after it was obtained"
to be discussed further

**Comment by aarongable** [comment]
I think the smallest possible change is:
> "For validation of Domain Names and IP Addresses according to Section 3.2.2.4 and 3.2.2.5, any ~~reused~~ data, document, or completed validation **used** MUST be obtained no more than 398 days prior to issuing the Certificate."

I suggest we do this, as it removes all ambiguity regarding "reuse" while changing nothing else.
