### ISSUE TITLE
BR v2.0.0 Redline Inconsistent Naming

### ISSUE THREAD

**Issue by AaronP-ATS** [cabforum/servercert#445]
Minor issue, but the redlined v2.0.0 of the BRs is named "BR-SC62-redlined.pdf". For consistency with other BR versions, it should follow the historical convention of "CA-Browser-Forum-BR-x.x.x-redline.pdf".

![br_v2-0-0_filenameDiscrep](https://github.com/cabforum/servercert/assets/109612620/6f2cb888-c925-4970-a101-f9d6d74942a0)

**Comment by barrini** [comment]
thanks for spotting this. Fixed.
