### ISSUE TITLE
IP validation via ACME

### ISSUE THREAD

**Issue by timfromdigicert** [cabforum/servercert#446]
The BRs reference a draft RFC for IP validation (https://tools.ietf.org/html/draft‐ietf‐acme‐ip‐04#section‐4).  That draft has since been published as RFC 8738.  We should look if the reference can be updated to point to the published RFC instead of the draft.

**Comment by barrini** [comment]
to include in the next clean-up ballot

**Comment by barrini** [comment]
Reflected in #169 
Already included in the clean-up
