### ISSUE TITLE
Clarify "specified above" in section 6.2

### ISSUE THREAD

**Issue by wthayer** [cabforum/servercert#450]
The second sentence of BR section 6.2 states: Protection of the CA Private Key outside the validated system or device specified above MUST consist of physical security, encryption, or a combination of both, implemented in a manner that prevents disclosure of the Private Key.

It's not clear to me what "the validated system or device specified above" is referring to. Looking back 8 years, I see that this sentence used to be in section 16.6 and was preceded by the statement "The CA SHALL protect its Private Key in a system or device that has been validated as meeting at least FIPS 140 level 3 or an appropriate Common Criteria Protection Profile or Security Target, EAL 4 (or higher), which includes requirements to protect the Private Key and other assets against known threats." When the BRs were restructured to RFC 3647 format, that sentence was moved below (section 6.2.7).

I believe the fix is to simply replace "specified above" with "specified in section 6.2.7"

**Comment by barrini** [comment]
to include in the next clean-up ballot
