### ISSUE TITLE
Clarify CA Subscribers

### ISSUE THREAD

**Issue by BenWilson-Mozilla** [cabforum/servercert#453]
Modified from https://lists.cabforum.org/pipermail/validation/2022-November/001826.html:

Here is draft language that could be added to BR Section 1.3.3, Subscribers.

In some situations, a CA acts as an Applicant or Subscriber, for instance, when it generates and protects a Private Key, requests a Certificate, demonstrates control of a Domain, or obtains a Certificate for its own use.

**Comment by BenWilson-Mozilla** [comment]
Perhaps this language might make it more clear that a CA must store validation records under BR section 5.4.1 when it is also the Subscriber.

**Comment by barrini** [comment]
to include in the next clean-up ballot
