### ISSUE TITLE
Amend 3.2.5 to not require IV validation for DV certificates

### ISSUE THREAD

**Issue by CBonnell** [cabforum/servercert#457]
It was mentioned on a validation-sc call that 3.2.5 could be read to require IV validation per 3.2.3 for DV certificates. Clearly this is not intended, so we should revisit this language and make it clear this is not required.

**Comment by clintwilson** [comment]
Specifically, I believe it's this in 3.2.5 that's potentially problematic
> If the Applicant for a Certificate containing Subject Identity Information is an organization, the CA SHALL use a Reliable Method of Communication to verify the authenticity of the Applicant Representative's certificate request.

**Comment by XolphinMartijn** [comment]
"Subject Identity Information" however states:
**Subject Identity Information**: Information that identifies the Certificate Subject. Subject Identity Information does not include a Domain Name listed in the `subjectAltName` extension or the Subject `commonName` field.

That would exclude DV certs I would say, unless the CA included subject:countryName in the DV Cert (currently allowed). 
I don't directly see this as problematic?

**Comment by CBonnell** [comment]
I think that detail regarding the Defined Term was missed during the discussion. Given that definition, I think this can be closed.

**Comment by CBonnell** [comment]
This issue was addressing some language that seemingly required IV validation for DV certificates. However, it was determined that no changes are needed.

A separate issue will be created to consider removal of the `C` attribute from DV certificates.
