### ISSUE TITLE
Minor grammatical error in 7.1.2.11.4 Subject Key Identifier

### ISSUE THREAD

**Issue by clintwilson** [cabforum/servercert#461]
This section contains the following sentence:

> For example, CAs may generate the subject key identifier using an algorithm derived from the public key, or may generate a sufficiently-large unique number, such by using a CSPRNG.

I think the final clause is either missing an "as" or has an erroneous "such" included, i.e.

> For example, CAs may generate the subject key identifier using an algorithm derived from the public key, or may generate a sufficiently-large unique number, such as by using a CSPRNG.

OR
> For example, CAs may generate the subject key identifier using an algorithm derived from the public key, or may generate a sufficiently-large unique number, by using a CSPRNG.

**Comment by romanf** [comment]
Well spotted! Personally I prefer the second version (safe 7 bytes... ;) )

**Comment by barrini** [comment]
included in the clean-up ballot
