### ISSUE TITLE
Inconsistent document formatting (Markdown vs PDF)

### ISSUE THREAD

**Issue by ryancdickson** [cabforum/servercert#462]
**Issue:** The formatting of bulleted lists observed in the Markdown version of the TLS BRs does not convey to the PDF version.

**Specific example:**
- Markdown: https://github.com/cabforum/servercert/blob/main/docs/BR.md#712112-crl-distribution-points
- PDF: https://cabforum.org/wp-content/uploads/CA-Browser-Forum-BR-v2.0.1.pdf (See 7.1.2.11.2)
- Note: In the PDF Version, the following text does not appear as a bulleted list, whereas in the Markdown version it does (intended format).

> The CRL Distribution Points extension MUST be present in: ‐ Subordinate CA Certificates; and ‐
Subscriber Certificates that 1) do not qualify as “Short‐lived Subscriber Certificates” and 2) do not
include an Authority Information Access extension with an id‐ad‐ocsp accessMethod.

@barrini - perhaps if there's another round of discussion on the clean-up ballot, this could be considered in scope.

**Comment by barrini** [comment]
I think is in scope, it´s just a typo, and still on time. Do you want to include it?

**Comment by barrini** [comment]
Jos gave a suggestion on the yesterday´s infra call to solve this. I tested it in my branch and it worked it so I will include in the final version if the ballot SC66 passess.

**Comment by dzacharo** [comment]
@barrini even for such a small change, according to the Bylaws you would need another round of discussion, as Ryan said in https://github.com/cabforum/servercert/issues/462#issue-1947515866.
