### ISSUE TITLE
Clarify that defined terms which are singular apply to usages of the term which are plural

### ISSUE THREAD

**Issue by dzacharo** [cabforum/servercert#468]
Nit:

There is a definition for "High Risk Certificate Request" but the document uses the capitalized term "High Risk Certificate Request**s**". 

We should either change the definition to "High Risk Certificate Requests" or the capitalized term throughout the document.

**Comment by bcmorton** [comment]
Sorry, that is a Code Signing working group ballot.

**Comment by XolphinMartijn** [comment]
@dzacharo I believe we have this problem with quite a number of definitions and usages:

Application Software Supplier is used several times as Application Software Suppliers
Authorization Domain Name / Authorization Domain Names

I could probably go on searching. Would it make more sense to clarify that capitalized terms can be used as plural?

**Comment by dzacharo** [comment]
It certainly helps to search the exact definition throughout the document. I understand the challenges and effort necessary to clean-up this and similar issues but we will be working on the definitions in the RFC 3647 conversion, effort lead by @barrini, and the import of EV Guidelines into the Code Signing BRs. 

I would prefer leaving this as an open item to tackle later as an improvement but we can certainly add a clarification like the one suggested by @XolphinMartijn.

Thoughts?
