### ISSUE TITLE
Inconsistency in the use of policyQualifiers in the EVGs and TLS BRs

### ISSUE THREAD

**Issue by ChristopherRC** [cabforum/servercert#469]
Section[ 9.7. Additional Technical Requirements for EV Certificates](https://github.com/cabforum/servercert/blob/main/docs/EVG.md#97-additional-technical-requirements-for-ev-certificates) of the EVGs states policyQualifiers is **required** for Subscriber certificates. With Ballot SC62, Section[ 7.1.2.7.9 Subscriber Certificate Certificate Policies](https://github.com/cabforum/servercert/blob/main/docs/BR.md#71279-subscriber-certificate-certificate-policies) of the TLS BRs states policyQualifiers are **NOT RECOMMENDED** for Subscriber certificates. 

Should this section of the EVGs be updated to align with the TLS BRs?

**Comment by XolphinMartijn** [comment]
+1. It seems unnecesairy for CAs that want to follow the NOT RECOMMENDED, to have to implement different logic for EV certificates.

**Comment by barrini** [comment]
Covered by ballot SC72
